version: '3.7'
services:

  web:
    build:
      context: .
      dockerfile: container-build/web/Dockerfile
    environment:
      - MYSQL_DATABASE=dbname
      - MYSQL_USER=dbuser
      - MYSQL_PASSWORD=654321
    ports:
      - "8080:80"
    volumes:
      - .:/var/www
    depends_on:
      - db

  db:
    image: mariadb
    ports:
      - 3306:3306
    environment:
      - MYSQL_ROOT_PASSWORD=654321
      - MYSQL_USER=dbuser
      - MYSQL_PASSWORD=654321
      - MYSQL_DATABASE=dbname
    volumes:
      - ${PWD}/mariadb:/var/lib/mysql

volumes:
  mysql_data: {
    driver: local
  }